### ISSUE TITLE
Set shortcode name for Code Snippet

### ISSUE THREAD

**Issue by marbetschar** [jtsternberg/Code-Snippets-CPT#19]
It would be cool to set a shortcode for a Code Snippet for later used from within a blog post for example.
Maybe this should just be possible for the PHP language.

For example to define a shortcode `[current_year]` as follows:

```
echo date("Y");
```

**Comment by marbetschar** [comment]
It is maybe just enough to check the Code Snippet as "Shortcode" and the slug could be used as shortcode name. So adding a setting "Shortcode true/false" should be enough!

**Comment by jtsternberg** [comment]
This plugin is exclusively for displaying snippets, not running them. There are other snippet plugins out there for executing code, and I don't want to take on that liability. Here is one I have seen by Crowd Favorite: https://github.com/crowdfavorite/wp-cf-snippets

**Comment by marbetschar** [comment]
Ok!
