### ISSUE TITLE
Conflict with Easy Digital Downloads

### ISSUE THREAD

**Issue by vegasgeek** [jtsternberg/Code-Snippets-CPT#28]
I've been trying to track down an issue on a site for a couple days, and today I had a bit of a breakthrough.

When I'm logged in and on the main dashboard page, in the console I'm receiving an error that looks like this:

![image](https://cloud.githubusercontent.com/assets/367562/18218846/4e546444-711a-11e6-868f-92c7dc06b19b.png)

That error is not from Code Snippets directly. It's actually being spit out by EDD. However, I've found that if I disable Code Snippets, the error goes away.

Happy to provide any additional information you may want/need if it would help.

**Comment by jtsternberg** [comment]
Is there a public URL I can see this? The plugin doesn't use tooltips, but hopefully a good clue.

**Comment by jtsternberg** [comment]
This only occurs in the dashboard?

**Comment by vegasgeek** [comment]
It's only happening on the dashboard, correct. Happy to screenshare with you if you'd like.

**Comment by jtsternberg** [comment]
Just pushed an update, and should fix the issues.

**Comment by vegasgeek** [comment]
That did the trick Thanks!
