### ISSUE TITLE
Admin submenu word adjustment

### ISSUE THREAD

**Issue by deviodigital** [jtsternberg/Code-Snippets-CPT#31]
I noticed that when the plugin's submenu pops out on hover, the "Add New Code Snippet" text drops to two lines.

![image](https://user-images.githubusercontent.com/9917957/27554266-dfb98d7e-5a7b-11e7-9bbf-3974edac5ee4.png)

This doesn't happen when the main menu item is open and all submenu items are in view.

![image](https://user-images.githubusercontent.com/9917957/27554306-05ad806c-5a7c-11e7-99e6-aff94767e2b2.png)

But it does happen when the "Add New Code Snippet" submenu item is selected.

![image](https://user-images.githubusercontent.com/9917957/27554341-1f3b9aa0-5a7c-11e7-9762-7bce597a3009.png)

I updated it to show "Add New Snippet", which keeps it on one line in both instances [here](https://github.com/deviodigital/Code-Snippets-CPT/commit/df7920e2195ac1fe5993e1cb83d92bbb0c2912db).

Can submit a PR if you feel it's worth updating.

**Comment by jtsternberg** [comment]
Sure, I'll take a PR if you're up for it. Thanks.

**Comment by deviodigital** [comment]
ok great. taking care of that now 👍
